!----------------------------------------------------------------------
      MODULE indijk_module
!----------------------------------------------------------------------
!
      INTEGER, PARAMETER :: ip0_jp0_kp0_ =   1   ! ijk      ! c
      INTEGER, PARAMETER :: ip1_jp0_kp0_ =   2   ! ipjk     ! e
      INTEGER, PARAMETER :: im1_jp0_kp0_ =   3   ! imjk     ! w
      INTEGER, PARAMETER :: ip2_jp0_kp0_ =   4   ! ippjk    ! ee
      INTEGER, PARAMETER :: im2_jp0_kp0_ =   5   ! immjk    ! ww
      INTEGER, PARAMETER :: ip0_jp1_kp0_ =   6   ! ijpk     ! n
      INTEGER, PARAMETER :: ip1_jp1_kp0_ =   7   ! ipjpk    ! en
      INTEGER, PARAMETER :: im1_jp1_kp0_ =   8   ! imjpk    ! wn
      INTEGER, PARAMETER :: ip0_jm1_kp0_ =   9   ! ijmk     ! s
      INTEGER, PARAMETER :: ip1_jm1_kp0_ =  10   ! ipjmk    ! es
      INTEGER, PARAMETER :: im1_jm1_kp0_ =  11   ! imjmk    ! ws
      INTEGER, PARAMETER :: ip0_jp2_kp0_ =  12   ! ijppk    ! nn
      INTEGER, PARAMETER :: ip0_jm2_kp0_ =  13   ! ijmmk    ! ss
      INTEGER, PARAMETER :: ip0_jp0_kp1_ =  14   ! ijkp     ! t
      INTEGER, PARAMETER :: ip1_jp0_kp1_ =  15   ! ipjkp    ! et
      INTEGER, PARAMETER :: im1_jp0_kp1_ =  16   ! imjkp    ! wt
      INTEGER, PARAMETER :: ip0_jp1_kp1_ =  17   ! ijpkp    ! nt
      INTEGER, PARAMETER :: ip0_jm1_kp1_ =  18   ! ijmkp    ! st
      INTEGER, PARAMETER :: ip0_jp0_km1_ =  19   ! ijkm     ! b
      INTEGER, PARAMETER :: ip1_jp0_km1_ =  20   ! ipjkm    ! eb
      INTEGER, PARAMETER :: im1_jp0_km1_ =  21   ! imjkm    ! wb
      INTEGER, PARAMETER :: ip0_jp1_km1_ =  22   ! ijpkm    ! nb
      INTEGER, PARAMETER :: ip0_jm1_km1_ =  23   ! ijmkm    ! sb
      INTEGER, PARAMETER :: ip0_jp0_kp2_ =  24   ! ijkpp    ! tt
      INTEGER, PARAMETER :: ip0_jp0_km2_ =  25   ! ijkmm    ! bb 
      INTEGER, PARAMETER :: im1_jm1_kp1_ =  26   ! imjmkp   ! wst 
      INTEGER, PARAMETER :: ip1_jm1_kp1_ =  27   ! ipjmkp   ! est
      INTEGER, PARAMETER :: im1_jp1_kp1_ =  28   ! imjpkp   ! wnt
      INTEGER, PARAMETER :: ip1_jp1_kp1_ =  29   ! ipjpkp   ! ent
      INTEGER, PARAMETER :: ip1_jp1_km1_ =  30   ! ipjpkm   ! enb
      INTEGER, PARAMETER :: ip1_jm1_km1_ =  31   ! ipjmkm   ! esb
      INTEGER, PARAMETER :: im1_jp1_km1_ =  32   ! imjpkm   ! wnb
      INTEGER, PARAMETER :: ip0_jm2_kp1_ =  33   ! ijmmkp   ! sst
      INTEGER, PARAMETER :: ip2_jp0_kp1_ =  34   ! ippjkp   ! eet 
      INTEGER, PARAMETER :: ip2_jp0_km1_ =  35   ! ippjkm   ! eeb
      INTEGER, PARAMETER :: ip1_jp0_kp2_ =  36   ! ipjkpp   ! ett
      INTEGER, PARAMETER :: im1_jp0_kp2_ =  37   ! imjkpp   ! wtt
      INTEGER, PARAMETER :: ip2_jp1_kp0_ =  38   ! ippjpk   ! een
      INTEGER, PARAMETER :: ip2_jm1_kp0_ =  39   ! ippjmk   ! ees
      INTEGER, PARAMETER :: ip1_jm2_kp0_ =  40   ! ipjmmk   ! ess
      INTEGER, PARAMETER :: ip0_jp2_kp1_ =  41   ! ijppkp   ! nnt
      INTEGER, PARAMETER :: ip1_jp2_kp0_ =  42   ! ipjppk   ! enn
      INTEGER, PARAMETER :: ip1_jp0_km2_ =  43   ! ipjkmm   ! ebb
      INTEGER, PARAMETER :: im1_jp2_kp0_ =  44   ! imjppk   ! wnn
      INTEGER, PARAMETER :: ip0_jp1_km2_ =  45   ! ijpkmm   ! nbb
      INTEGER, PARAMETER :: ip0_jp2_km1_ =  46   ! ijppkm   ! nnb
      INTEGER, PARAMETER :: ip0_jm1_kp2_ =  47   ! ijmkpp   ! stt
      INTEGER, PARAMETER :: ip0_jp1_kp2_ =  48   ! ijpkpp   ! ntt
      INTEGER, PARAMETER :: im2_jp1_kp0_ =  49   ! immjpk   ! wwn
      INTEGER, PARAMETER :: im2_jp0_kp1_ =  50   ! immjkp   ! wwt
      INTEGER, PARAMETER :: im1_jm1_km1_ =  51   ! imjmkm   ! wsb
      INTEGER, PARAMETER :: ip1_jm2_kp1_ =  52   ! ipjmmkp  ! esst
      INTEGER, PARAMETER :: ip2_jp1_km1_ =  53   ! ippjpkm  ! eenb
      INTEGER, PARAMETER :: ip2_jm1_km1_ =  54   ! ippjmkm  ! eesb
      INTEGER, PARAMETER :: ip2_jm1_kp1_ =  55   ! ippjmkp  ! eest
      INTEGER, PARAMETER :: im1_jp2_kp1_ =  56   ! imjppkp  ! wnnt
      INTEGER, PARAMETER :: ip1_jp2_km1_ =  57   ! ipjppkm  ! ennb
      INTEGER, PARAMETER :: ip1_jp1_km2_ =  58   ! ipjpkmm  ! enbb
      INTEGER, PARAMETER :: im1_jp2_km1_ =  59   ! imjppkm  ! wnnb
      INTEGER, PARAMETER :: im1_jm1_kp2_ =  60   ! imjmkpp  ! wstt
      INTEGER, PARAMETER :: im1_jp1_kp2_ =  61   ! imjpkpp  ! wntt
      INTEGER, PARAMETER :: ip1_jm1_kp2_ =  62   ! ipjmkpp  ! estt
      INTEGER, PARAMETER :: im2_jp1_kp1_ =  63   ! immjpkp  ! wwnt
      INTEGER, PARAMETER :: ip2_jp1_kp1_ =  64   ! ippjpkp  ! eent
      INTEGER, PARAMETER :: ip1_jp2_kp1_ =  65   ! ipjppkp  ! ennt
      INTEGER, PARAMETER :: ip1_jp1_kp2_ =  66   ! ipjpkpp  ! entt
      INTEGER, PARAMETER :: im1_jp0_km2_ =  67   ! imjkmm   ! wbb
      INTEGER, PARAMETER :: ip0_jm2_km1_ =  68   ! ijmmkm   ! ssb
      INTEGER, PARAMETER :: im2_jm1_kp0_ =  69   ! immjmk   ! wws
      INTEGER, PARAMETER :: ip0_jm1_km2_ =  70   ! ijmkmm   ! sbb
      INTEGER, PARAMETER :: im1_jm2_kp0_ =  71   ! imjmmk   ! wss
      INTEGER, PARAMETER :: im2_jp0_km1_ =  72   ! immjkm   ! wwb
      INTEGER, PARAMETER :: im1_jp1_km2_ =  73   ! imjpkmm  ! wnbb
      INTEGER, PARAMETER :: ip1_jm2_km1_ =  74   ! ipjmmkm  ! essb
      INTEGER, PARAMETER :: im2_jm1_kp1_ =  75   ! immjmkp  ! wwst
      INTEGER, PARAMETER :: ip1_jm1_km2_ =  76   ! ipjmkmm  ! esbb
      INTEGER, PARAMETER :: im1_jm1_km2_ =  77   ! imjmkmm  ! wsbb
      INTEGER, PARAMETER :: im1_jm2_km1_ =  78   ! imjmmkm  ! wssb
      INTEGER, PARAMETER :: im1_jm2_kp1_ =  79   ! imjmmkp  ! wsst
      INTEGER, PARAMETER :: im2_jp1_km1_ =  80   ! immjpkm  ! wwnb
      INTEGER, PARAMETER :: im2_jm1_km1_ =  81   ! immjmkm  ! wwsb
      INTEGER, PARAMETER :: ip1_jp1_kp3_ =  82   ! ipjpkppp ! enttt
      INTEGER, PARAMETER :: im1_jp1_kp3_ =  83   ! imjpkppp ! wnttt
      INTEGER, PARAMETER :: ip0_jp1_kp3_ =  84   ! ijpkppp  ! nttt 
      INTEGER, PARAMETER :: ip1_jp0_kp3_ =  85   ! ipjkppp  ! ettt 
      INTEGER, PARAMETER :: im1_jp0_kp3_ =  86   ! imjkppp  ! wttt 
      INTEGER, PARAMETER :: ip0_jp0_kp3_ =  87   ! ijkppp   ! ttt  
      INTEGER, PARAMETER :: ip1_jm2_kp2_ =  88   ! ipjmmkpp ! esstt
      INTEGER, PARAMETER :: ip0_jm2_kp2_ =  89   ! ijmmkpp  ! sstt 
      INTEGER, PARAMETER :: ip1_jp2_kp2_ =  90   ! ipjppkpp ! enntt
      INTEGER, PARAMETER :: ip0_jp2_kp2_ =  91   ! ijppkpp  ! nntt 
      INTEGER, PARAMETER :: im2_jm1_kp2_ =  92   ! immjmkpp ! wwstt
      INTEGER, PARAMETER :: im2_jp1_kp2_ =  93   ! immjpkpp ! wwntt
      INTEGER, PARAMETER :: im2_jp0_kp2_ =  94   ! immjkpp  ! wwtt 
      INTEGER, PARAMETER :: ip2_jm1_kp2_ =  95   ! ippjmkpp ! eestt
      INTEGER, PARAMETER :: ip2_jp1_kp2_ =  96   ! ippjpkpp ! eentt
      INTEGER, PARAMETER :: ip2_jp0_kp2_ =  97   ! ippjkpp  ! eett 
      INTEGER, PARAMETER :: ip1_jp3_km1_ =  98   ! ipjpppkm ! ennnb
      INTEGER, PARAMETER :: ip1_jp3_kp1_ =  99   ! ipjpppkp ! ennnt 
      INTEGER, PARAMETER :: ip0_jp3_km1_ = 100   ! ijpppkm  ! nnnb
      INTEGER, PARAMETER :: ip0_jp3_kp1_ = 101   ! ijpppkp  ! nnnt
      INTEGER, PARAMETER :: ip1_jp3_kp0_ = 102   ! ipjpppk  ! ennn
      INTEGER, PARAMETER :: ip0_jp3_kp0_ = 103   ! ijpppk   ! nnn  
      INTEGER, PARAMETER :: ip1_jp2_km2_ = 104   ! ipjppkmm ! ennbb
      INTEGER, PARAMETER :: im1_jp2_km2_ = 105   ! imjppkmm ! wnnbb
      INTEGER, PARAMETER :: ip0_jp2_km2_ = 106   ! ijppkmm  ! nnbb
      INTEGER, PARAMETER :: im1_jp2_kp2_ = 107   ! imjppkpp ! wnntt
      INTEGER, PARAMETER :: im2_jp2_kp1_ = 108   ! immjppkp ! wwnnt
      INTEGER, PARAMETER :: im2_jp2_kp0_ = 109   ! immjppk  ! wwnn 
      INTEGER, PARAMETER :: ip2_jp2_kp1_ = 110   ! ippjppkp ! eennt
      INTEGER, PARAMETER :: ip2_jp2_kp0_ = 111   ! ippjppk  ! eenn
      INTEGER, PARAMETER :: ip2_jp1_km2_ = 112   ! ippjpkmm ! eenbb
      INTEGER, PARAMETER :: ip2_jp0_km2_ = 113   ! ippjkmm  ! eebb 
      INTEGER, PARAMETER :: ip2_jm2_km1_ = 114   ! ippjmmkm ! eessb
      INTEGER, PARAMETER :: ip2_jm2_kp1_ = 115   ! ippjmmkp ! eesst
      INTEGER, PARAMETER :: ip2_jm2_kp0_ = 116   ! ippjmmk  ! eess 
      INTEGER, PARAMETER :: ip2_jp2_km1_ = 117   ! ippjppkm ! eennb
      INTEGER, PARAMETER :: ip3_jm1_kp1_ = 118   ! ipppjmkp ! eeest
      INTEGER, PARAMETER :: ip3_jp1_kp1_ = 119   ! ipppjpkp ! eeent
      INTEGER, PARAMETER :: ip3_jp0_kp1_ = 120   ! ipppjkp  ! eeet
      INTEGER, PARAMETER :: ip3_jm1_kp0_ = 121   ! ipppjmk  ! eees
      INTEGER, PARAMETER :: ip3_jp1_kp0_ = 122   ! ipppjpk  ! eeen
      INTEGER, PARAMETER :: ip3_jp0_kp0_ = 123   ! ipppjk   ! eee  
      INTEGER, PARAMETER :: im2_jp0_km2_ = 124   ! immjkmm  ! wwbb
      INTEGER, PARAMETER :: im2_jm2_kp0_ = 125   ! immjmmk  ! wwss
      INTEGER, PARAMETER :: ip0_jm2_km2_ = 126   ! ijmmkmm  ! ssbb
      INTEGER, PARAMETER :: ip3_jp0_km1_ = 127   ! ipppjkm  ! eeeb
      INTEGER, PARAMETER :: ip3_jp1_km1_ = 128   ! ipppjpkm ! eeenb
      INTEGER, PARAMETER :: ip3_jm1_km1_ = 129   ! ipppjmkm ! eeesb
      INTEGER, PARAMETER :: im1_jp3_kp0_ = 130   ! imjpppk  ! wnnn
      INTEGER, PARAMETER :: im1_jp3_kp1_ = 131   ! imjpppkp ! wnnnt
      INTEGER, PARAMETER :: im1_jp3_km1_ = 132   ! imjpppkm ! wnnnb
      INTEGER, PARAMETER :: ip0_jm1_kp3_ = 133   ! ijmkppp  ! sttt
      INTEGER, PARAMETER :: ip1_jm1_kp3_ = 134   ! ipjmkppp ! esttt
      INTEGER, PARAMETER :: im1_jm1_kp3_ = 135   ! imjmkppp ! wsttt
      INTEGER, PARAMETER :: im2_jp2_km1_ = 136   ! immjppkm ! wwnnb
      INTEGER, PARAMETER :: im2_jm2_kp1_ = 137   ! immjmmkp ! wwsst
      INTEGER, PARAMETER :: im2_jm2_km1_ = 138   ! immjmmkm ! wwssb
      INTEGER, PARAMETER :: ip2_jm1_km2_ = 139   ! ippjmkmm ! eesbb
      INTEGER, PARAMETER :: im2_jp1_km2_ = 140   ! immjpkmm ! wwnbb
      INTEGER, PARAMETER :: im2_jm1_km2_ = 141   ! immjmkmm ! wwsbb
      INTEGER, PARAMETER :: im1_jm2_kp2_ = 142   ! imjmmkpp ! wsstt
      INTEGER, PARAMETER :: ip1_jm2_km2_ = 143   ! ipjmmkmm ! essbb
      INTEGER, PARAMETER :: im1_jm2_km2_ = 144   ! imjmmkmm ! wssbb

!
! Stencil Dimension
!
      INTEGER, PARAMETER :: nstdim = 144

      INTEGER :: indijk(-2:3,-2:3,-2:3)

!----------------------------------------------------------------------
      CONTAINS
!----------------------------------------------------------------------
      SUBROUTINE indijk_setup()

        indijk = 0
        indijk(  0,  0,  0 ) = ip0_jp0_kp0_
        indijk(  1,  0,  0 ) = ip1_jp0_kp0_
        indijk( -1,  0,  0 ) = im1_jp0_kp0_
        indijk(  2,  0,  0 ) = ip2_jp0_kp0_
        indijk( -2,  0,  0 ) = im2_jp0_kp0_
        indijk(  0,  1,  0 ) = ip0_jp1_kp0_
        indijk(  1,  1,  0 ) = ip1_jp1_kp0_
        indijk( -1,  1,  0 ) = im1_jp1_kp0_
        indijk(  0, -1,  0 ) = ip0_jm1_kp0_
        indijk(  1, -1,  0 ) = ip1_jm1_kp0_
        indijk( -1, -1,  0 ) = im1_jm1_kp0_
        indijk(  0,  2,  0 ) = ip0_jp2_kp0_
        indijk(  0, -2,  0 ) = ip0_jm2_kp0_
        indijk(  0,  0,  1 ) = ip0_jp0_kp1_
        indijk(  1,  0,  1 ) = ip1_jp0_kp1_
        indijk( -1,  0,  1 ) = im1_jp0_kp1_
        indijk(  0,  1,  1 ) = ip0_jp1_kp1_
        indijk(  0, -1,  1 ) = ip0_jm1_kp1_
        indijk(  0,  0, -1 ) = ip0_jp0_km1_
        indijk(  1,  0, -1 ) = ip1_jp0_km1_
        indijk( -1,  0, -1 ) = im1_jp0_km1_
        indijk(  0,  1, -1 ) = ip0_jp1_km1_
        indijk(  0, -1, -1 ) = ip0_jm1_km1_
        indijk(  0,  0,  2 ) = ip0_jp0_kp2_
        indijk(  0,  0, -2 ) = ip0_jp0_km2_
        indijk(  2,  0,  1 ) = ip2_jp0_kp1_
        indijk(  2,  0, -1 ) = ip2_jp0_km1_
        indijk(  1,  0,  2 ) = ip1_jp0_kp2_
        indijk( -1,  0,  2 ) = im1_jp0_kp2_
        indijk( -1, -1,  1 ) = im1_jm1_kp1_ 
        indijk(  1, -1,  1 ) = ip1_jm1_kp1_
        indijk( -1,  1,  1 ) = im1_jp1_kp1_
        indijk(  1,  1,  1 ) = ip1_jp1_kp1_
        indijk(  1,  1, -1 ) = ip1_jp1_km1_
        indijk(  1, -1, -1 ) = ip1_jm1_km1_
        indijk( -1,  1, -1 ) = im1_jp1_km1_
        indijk(  0, -2,  1 ) = ip0_jm2_kp1_
        indijk(  2,  1,  0 ) = ip2_jp1_kp0_
        indijk(  2, -1,  0 ) = ip2_jm1_kp0_
        indijk(  1, -2,  0 ) = ip1_jm2_kp0_
        indijk(  1, -2,  1 ) = ip1_jm2_kp1_
        indijk(  2,  1, -1 ) = ip2_jp1_km1_
        indijk(  2, -1, -1 ) = ip2_jm1_km1_
        indijk(  2, -1,  1 ) = ip2_jm1_kp1_
        indijk( -1,  2,  1 ) = im1_jp2_kp1_
        indijk(  0,  2,  1 ) = ip0_jp2_kp1_
        indijk(  1,  2, -1 ) = ip1_jp2_km1_
        indijk(  1,  2,  0 ) = ip1_jp2_kp0_
        indijk(  1,  0, -2 ) = ip1_jp0_km2_
        indijk(  1,  1, -2 ) = ip1_jp1_km2_
        indijk( -1,  2, -1 ) = im1_jp2_km1_
        indijk( -1,  2,  0 ) = im1_jp2_kp0_
        indijk(  0,  1, -2 ) = ip0_jp1_km2_
        indijk(  0,  2, -1 ) = ip0_jp2_km1_
        indijk( -1, -1,  2 ) = im1_jm1_kp2_
        indijk(  0, -1,  2 ) = ip0_jm1_kp2_
        indijk( -1,  1,  2 ) = im1_jp1_kp2_
        indijk(  0,  1,  2 ) = ip0_jp1_kp2_
        indijk(  1, -1,  2 ) = ip1_jm1_kp2_
        indijk( -2,  1,  0 ) = im2_jp1_kp0_
        indijk( -2,  1,  1 ) = im2_jp1_kp1_
        indijk( -2,  0,  1 ) = im2_jp0_kp1_
        indijk( -1, -1, -1 ) = im1_jm1_km1_
        indijk(  2,  1,  1 ) = ip2_jp1_kp1_
        indijk(  1,  2,  1 ) = ip1_jp2_kp1_
        indijk(  1,  1,  2 ) = ip1_jp1_kp2_
        indijk( -1,  0, -2 ) = im1_jp0_km2_
        indijk(  0, -2, -1 ) = ip0_jm2_km1_
        indijk( -2, -1,  0 ) = im2_jm1_kp0_
        indijk(  0, -1, -2 ) = ip0_jm1_km2_
        indijk( -1, -2,  0 ) = im1_jm2_kp0_
        indijk( -2,  0, -1 ) = im2_jp0_km1_
        indijk( -1,  1, -2 ) = im1_jp1_km2_
        indijk(  1, -2, -1 ) = ip1_jm2_km1_
        indijk( -2, -1,  1 ) = im2_jm1_kp1_
        indijk(  1, -1, -2 ) = ip1_jm1_km2_
        indijk( -1, -1, -2 ) = im1_jm1_km2_
        indijk( -1, -2, -1 ) = im1_jm2_km1_
        indijk( -1, -2,  1 ) = im1_jm2_kp1_
        indijk( -2,  1, -1 ) = im2_jp1_km1_
        indijk( -2, -1, -1 ) = im2_jm1_km1_
        indijk(  1,  1,  3 ) = ip1_jp1_kp3_
        indijk( -1,  1,  3 ) = im1_jp1_kp3_
        indijk(  0,  1,  3 ) = ip0_jp1_kp3_
        indijk(  1,  0,  3 ) = ip1_jp0_kp3_
        indijk( -1,  0,  3 ) = im1_jp0_kp3_
        indijk(  0,  0,  3 ) = ip0_jp0_kp3_
        indijk(  1, -2,  2 ) = ip1_jm2_kp2_
        indijk(  0, -2,  2 ) = ip0_jm2_kp2_
        indijk(  1,  2,  2 ) = ip1_jp2_kp2_
        indijk(  0,  2,  2 ) = ip0_jp2_kp2_
        indijk( -2, -1,  2 ) = im2_jm1_kp2_
        indijk( -2,  1,  2 ) = im2_jp1_kp2_
        indijk( -2,  0,  2 ) = im2_jp0_kp2_
        indijk(  2, -1,  2 ) = ip2_jm1_kp2_
        indijk(  2,  1,  2 ) = ip2_jp1_kp2_
        indijk(  2,  0,  2 ) = ip2_jp0_kp2_
        indijk(  1,  3, -1 ) = ip1_jp3_km1_
        indijk(  1,  3,  1 ) = ip1_jp3_kp1_
        indijk(  0,  3, -1 ) = ip0_jp3_km1_
        indijk(  0,  3,  1 ) = ip0_jp3_kp1_
        indijk(  1,  3,  0 ) = ip1_jp3_kp0_
        indijk(  0,  3,  0 ) = ip0_jp3_kp0_
        indijk(  1,  2, -2 ) = ip1_jp2_km2_
        indijk( -1,  2, -2 ) = im1_jp2_km2_
        indijk(  0,  2, -2 ) = ip0_jp2_km2_
        indijk( -1,  2,  2 ) = im1_jp2_kp2_
        indijk( -2,  2,  1 ) = im2_jp2_kp1_
        indijk( -2,  2,  0 ) = im2_jp2_kp0_
        indijk(  2,  2,  1 ) = ip2_jp2_kp1_
        indijk(  2,  2,  0 ) = ip2_jp2_kp0_
        indijk(  2,  1, -2 ) = ip2_jp1_km2_
        indijk(  2,  0, -2 ) = ip2_jp0_km2_
        indijk(  2, -2, -1 ) = ip2_jm2_km1_
        indijk(  2, -2,  1 ) = ip2_jm2_kp1_
        indijk(  2, -2,  0 ) = ip2_jm2_kp0_
        indijk(  2,  2, -1 ) = ip2_jp2_km1_
        indijk(  3, -1,  1 ) = ip3_jm1_kp1_
        indijk(  3,  1,  1 ) = ip3_jp1_kp1_
        indijk(  3,  0,  1 ) = ip3_jp0_kp1_
        indijk(  3, -1,  0 ) = ip3_jm1_kp0_
        indijk(  3,  1,  0 ) = ip3_jp1_kp0_
        indijk(  3,  0,  0 ) = ip3_jp0_kp0_
        indijk( -2,  0, -2 ) = im2_jp0_km2_
        indijk( -2, -2,  0 ) = im2_jm2_kp0_
        indijk(  0, -2, -2 ) = ip0_jm2_km2_
        indijk(  3,  0, -1 ) = ip3_jp0_km1_
        indijk(  3,  1, -1 ) = ip3_jp1_km1_
        indijk(  3, -1, -1 ) = ip3_jm1_km1_
        indijk( -1,  3,  0 ) = im1_jp3_kp0_
        indijk( -1,  3,  1 ) = im1_jp3_kp1_
        indijk( -1,  3, -1 ) = im1_jp3_km1_
        indijk(  0, -1,  3 ) = ip0_jm1_kp3_
        indijk(  1, -1,  3 ) = ip1_jm1_kp3_
        indijk( -1, -1,  3 ) = im1_jm1_kp3_
        indijk( -2,  2, -1 ) = im2_jp2_km1_
        indijk( -2, -2,  1 ) = im2_jm2_kp1_
        indijk( -2, -2, -1 ) = im2_jm2_km1_
        indijk(  2, -1, -2 ) = ip2_jm1_km2_
        indijk( -2,  1, -2 ) = im2_jp1_km2_
        indijk( -2, -1, -2 ) = im2_jm1_km2_
        indijk( -1, -2,  2 ) = im1_jm2_kp2_
        indijk(  1, -2, -2 ) = ip1_jm2_km2_
        indijk( -1, -2, -2 ) = im1_jm2_km2_
        RETURN
      END SUBROUTINE 
!----------------------------------------------------------------------
      END MODULE
!----------------------------------------------------------------------
